### ISSUE TITLE
Problem attaching service to meteor.js

### ISSUE THREAD

**Issue by sirpravdi** [Streamedian/html5_rtsp_player#33] opened 2017-02-16 21:46 UTC
Hello
I tried to attach your service to my meteor.js project (it should work with npm according to documentation), but smth went wrong. 
This is the command: 
C:\Users\Bo\myapp>meteor npm install git://github.com/Streamedian/html5_rtsp_player.git

npm ERR! git clone C:\Users\Bo\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-Streamedian-html5-rtsp-player-git-9aa2085e C:\Users\Bo\AppData\Local\Temp\npm-50688-2c552762\git-cache-ce5e04b7\6207bc53008c1f70405fd7f52821ea5ec8115f0b: Cloning into 'C:\Users\Bo\AppData\Local\Temp\npm-50688-2c552762\git-cache-ce5e04b7\6207bc53008c1f70405fd7f52821ea5ec8115f0b'...
npm ERR! git clone C:\Users\Bo\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-Streamedian-html5-rtsp-player-git-9aa2085e C:\Users\Bo\AppData\Local\Temp\npm-50688-2c552762\git-cache-ce5e04b7\6207bc53008c1f70405fd7f52821ea5ec8115f0b: error: cannot spawn sh: No such file or directory
npm ERR! git clone C:\Users\Bo\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-Streamedian-html5-rtsp-player-git-9aa2085e C:\Users\Bo\AppData\Local\Temp\npm-50688-2c552762\git-cache-ce5e04b7\6207bc53008c1f70405fd7f52821ea5ec8115f0b: fatal: unable to fork
npm ERR! git clone C:\Users\Bo\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-Streamedian-html5-rtsp-player-git-9aa2085e C:\Users\Bo\AppData\Local\Temp\npm-50688-2c552762\git-cache-ce5e04b7\6207bc53008c1f70405fd7f52821ea5ec8115f0b:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Bo\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Bo\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "git://github.com/Streamedian/html5_rtsp_player.git"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\Bo\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\.npm\_git-remotes\git-github-com-Streamedian-html5-rtsp-player-git-9aa2085e C:\Users\Bo\AppData\Local\Temp\npm-50688-2c552762\git-cache-ce5e04b7\6207bc53008c1f70405fd7f52821ea5ec8115f0b
npm ERR! Cloning into 'C:\Users\Bo\AppData\Local\Temp\npm-50688-2c552762\git-cache-ce5e04b7\6207bc53008c1f70405fd7f52821ea5ec8115f0b'...
npm ERR! error: cannot spawn sh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Bo\myapp\npm-debug.log

Is it possible to attach it at all or am I doing smth wrong while attaching?

Thanks,
Olya

**Comment by kreopt** [comment] 2017-02-17 01:59
looks like you had not setup correct environment for npm:

> error: cannot spawn sh: No such file or directory

No unix shell was found so script failed to execute. You can try execute npm install not directly from windows cmd but from some unix evironment like git bash

**Comment by sirpravdi** [comment] 2017-02-19 19:50
I tried and followed your advice about installing via git bash, but it showed following mistakes:

$ meteor npm install git://github.com/Streamedian/html5_rtsp_player.git
npm ERR! git submodule -q update --init --recursive: C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 18: .: git-sh-setup: file not found
npm ERR! git submodule -q update --init --recursive:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Bo\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Bo\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_3\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "git://github.com/Streamedian/html5_rtsp_player.git"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code 1

npm ERR! Command failed: git -c core.longpaths=true submodule -q update --init --recursive
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 18: .: git-sh-setup: file not found
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Bo\myapp\npm-debug.log

**Comment by kreopt** [comment] 2017-02-21 02:33
There is definitely problem with your environment.
git-sh-setup: file not found -- now it missed that file.

Closing this issue as not a bug.

**Closed by kreopt** 2017-02-21 02:33 UTC
